package com.zerodelusions.shemsapi.enums;

public enum DeviceType {
    THERMOSTAT,
    LIGHT_BULB,
    SMART_PLUG,
    SECURITY_CAMERA,
    SMART_DOOR_LOCK,
    REFRIGERATOR,
    WASHING_MACHINE,
    DRYER,
    DISHWASHER,
    AIR_CONDITIONER,
    WATER_HEATER,
    OVEN,
    MICROWAVE,
    VACUUM_CLEANER,
    SMART_TV,
    FAN,
    SMART_SPEAKER,
    GARAGE_DOOR_OPENER,
    SMOKE_DETECTOR,
    SMART_SPRINKLER,
    ELECTRIC_CAR_CHARGER,
    HOME_BATTERY
}

